# Generated by Django 3.1.13 on 2025-02-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daywiseactivity',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
